version: "3"

services:
  backend:
    build:
      context: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
